### PR TITLE
Adds crypto, public_key and ssl start.

### PR DESCRIPTION
**Pull request by fgallaire**
Adds crypto, public_key and ssl start.

### CODE REVIEW

**Comment by essen** [comment]
I probably should remove that file, it's not used. Farwest is just a dependency to your project and is started by the release itself.

**Comment by fgallaire** [comment]
OK, I'm trying to test :-)
Farwest seems to be what I'm looking for since so long !

**Comment by essen** [comment]
A few weeks more and it should be usable without guessing. :)

**Comment by dmitriid** [comment]
Consider using approach used here: https://github.com/samuelrivas/samerlib/blob/master/src/sel_application.erl (see start_app) to start all desired applications

**Comment by essen** [comment]
We are going to use start phases as is done in the first PR.

**Comment by essen** [comment]
Oh, and the function start will be removed entirely, the release will take care of that.

**Comment by essen** [comment]
Closing. Thanks!

**Pull request closed without merging**
